return {
  -- 'kevinhwang91/nvim-ufo',
  -- dependencies = 'kevinhwang91/promise-async',
  -- event = 'BufRead',
  -- config = function()
  --   -- Fold options
  --   vim.o.foldcolumn = '1' -- 折りたたみ列を表示（'0'で非表示）
  --   vim.o.foldlevel = 99 -- 開いた状態で開始するレベル
  --   vim.o.foldlevelstart = 99 -- 新しいバッファで開始するレベル
  --   vim.o.foldenable = true -- 折りたたみを有効化
  --
  --   -- Using ufo provider need remap `zR` and `zM`.
  --   vim.keymap.set('n', 'zR', require('ufo').openAllFolds, { desc = 'Open all folds' })
  --   vim.keymap.set('n', 'zM', require('ufo').closeAllFolds, { desc = 'Close all folds' })
  --   -- zr と zm は標準の Vim の動作を使用（1レベルずつ開く/閉じる）
  --
  --   -- Preview fold
  --   vim.keymap.set('n', 'K', function()
  --     local winid = require('ufo').peekFoldedLinesUnderCursor()
  --     if not winid then
  --       -- キーマップが LSP hover にフォールバックする場合
  --       vim.lsp.buf.hover()
  --     end
  --   end, { desc = 'Peek folded lines or LSP hover' })
  --
  --   require('ufo').setup({
  --     -- Treesitter を優先、次に LSP、最後にインデントベースの折りたたみ
  --     provider_selector = function(bufnr, filetype, buftype)
  --       return {'treesitter', 'indent'}
  --     end,
  --     -- 折りたたみのプレビュー
  --     preview = {
  --       win_config = {
  --         border = {'', '─', '', '', '', '─', '', ''},
  --         winhighlight = 'Normal:Folded',
  --         winblend = 0
  --       },
  --       mappings = {
  --         scrollU = '<C-u>',
  --         scrollD = '<C-d>',
  --         jumpTop = '[',
  --         jumpBot = ']'
  --       }
  --     },
  --     -- 折りたたまれた行の表示設定
  --     fold_virt_text_handler = function(virtText, lnum, endLnum, width, truncate)
  --       local newVirtText = {}
  --       local suffix = (' ... %d lines'):format(endLnum - lnum)
  --       local sufWidth = vim.fn.strdisplaywidth(suffix)
  --       local targetWidth = width - sufWidth
  --       local curWidth = 0
  --       for _, chunk in ipairs(virtText) do
  --         local chunkText = chunk[1]
  --         local chunkWidth = vim.fn.strdisplaywidth(chunkText)
  --         if targetWidth > curWidth + chunkWidth then
  --           table.insert(newVirtText, chunk)
  --         else
  --           chunkText = truncate(chunkText, targetWidth - curWidth)
  --           local hlGroup = chunk[2]
  --           table.insert(newVirtText, {chunkText, hlGroup})
  --           chunkWidth = vim.fn.strdisplaywidth(chunkText)
  --           if curWidth + chunkWidth < targetWidth then
  --             suffix = suffix .. (' '):rep(targetWidth - curWidth - chunkWidth)
  --           end
  --           break
  --         end
  --         curWidth = curWidth + chunkWidth
  --       end
  --       table.insert(newVirtText, {suffix, 'MoreMsg'})
  --       return newVirtText
  --     end,
  --   })
  -- end,
}
